version: "3"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    privileged: true
    user: root
    environment:
    ports:
      - "2181:2181"
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - /opt/volumes/broker/zookeeper:/bitnami

  kafka:
    image: docker.io/bitnami/kafka:latest
    container_name: kafka
    hostname: kafka
    privileged: true
    user: root
    ports:
      - "9092:9092"
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - /opt/volumes/broker/kafka:/bitnami
    depends_on:
      - zookeeper

networks:
  default:
    name: broker