version: "3"

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    hostname: zookeeper
    user: root
    ports:
      - "2181:2181"
    environment:
      - TZ=Asia/Shanghai
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - /opt/volumes/broker/zookeeper:/bitnami/zookeeper

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    hostname: kafka
    user: root
    ports:
      - "9092:9092"
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - /opt/volumes/broker/kafka:/bitnami/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

networks:
  default:
    name: broker