version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    hostname: mongo
    tty: true
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - /opt/mongo/db:/data/db
      - /opt/mongo/log:/var/log
      - /opt/mongo/conf:/data/configdb

#  mongo-express:
#    container_name: mongo_express
#    image: mongo-express:latest
#    hostname: express
#    tty: true
#    ports:
#      - "${MOGO_EXPRESS_PORT:-8081}:8081"
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: root
#      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/

networks:
  default:
    name: machine
