version: "3.8"

services:
  nats:
    container_name: nats
    image: nats:latest
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "${NATS_CLIENT_PORT:-4222}:4222"
      - "${NATS_CLUSTER_PORT:-6222}:6222"
      - "${NATS_HTTP_PORT:-8222}:8222"
    networks:
      - default

networks:
  default:
    name: bridge-default
    driver: bridge
    external: true
