version: "3.8"

services:
  nats:
    image: nats:latest
    container_name: nats
    hostname: nats
    restart: always
    entrypoint: /nats-server
    command: --js --sd /data
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "${NATS_CLIENT_PORT:-4222}:4222"
      - "${NATS_CLUSTER_PORT:-6222}:6222"
      - "${NATS_HTTP_PORT:-8222}:8222"
    volumes:
      - /opt/nats:/data

networks:
  default:
    name: machine
