version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - /opt/nginx/nginx.pid:/var/run/nginx.pid
      - /opt/nginx/logs:/var/log/nginx
#    ports:

networks:
  default:
    name: machine