version: "3.8"

# Portainer-CN
# git clone https://github.com/charlesbases/Portainer-CN.git /opt/volumes/portainer/public

services:
  portainer:
    image: portainer/portainer:latest
    container_name: portainer
    hostname: portainer
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /opt/volumes/portainer/data:/data
      - /opt/volumes/portainer/public:/public
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${PORTAINER_PORT:-9000}:9000"

networks:
  default:
    name: machine