version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    user: root
    privileged: true
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - /opt/volumes/postgres/data:/var/lib/postgresql/data/

networks:
  default:
    name: machine
